sudo: required
dist: trusty
os: linux
group: stable
language: node_js
node_js: 6.10.3

services: mongodb


before_install:
  - mongo data --eval 'db.dropDatabase();'
  - sudo apt-get update
  - sudo apt-get install wget python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev libc6-dev git -y
  - wget https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz -O ipfs.tar.gz
  - tar xvfz ipfs.tar.gz
  - sudo mv go-ipfs/ipfs /usr/local/bin/ipfs
  - ipfs init
  - git clone https://github.com/ega-forever/Middleware.git -b develop
  - npm install --prefix Middleware
  - npm run prepare_linux_install --prefix Middleware
  - npm run testrpc --prefix Middleware  > /dev/null &
  - sleep 30 && npm run test --prefix Middleware


install:
  - npm install

script:
  - npm run test -- --coverage

notifications:
  email: false

cache:
  directories:
    - node_modules