sudo: required
dist: trusty
os: linux
group: stable
language: node_js
node_js: 6.10.3

services: mongodb


before_install:
  - mongo data --eval 'db.dropDatabase();'
  - sudo apt-get update
  - sudo apt-get install wget python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev libc6-dev git -y
  - wget https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz -O ipfs.tar.gz
  - tar xvfz ipfs.tar.gz
  - sudo mv go-ipfs/ipfs /usr/local/bin/ipfs
  - ipfs init
  - ipfs daemon > /dev/null &

install:
  - npm install
  - node ./node_modules/middleware/ipcConverter.js | node ./node_modules/ethereumjs-testrpc/bin/testrpc > /dev/null &
  - mkdir -p $TRAVIS_BUILD_DIR/node_modules/middleware/node_modules
  - cp -ax $TRAVIS_BUILD_DIR/node_modules/chronobank-smart-contracts $TRAVIS_BUILD_DIR/node_modules/middleware/node_modules/chronobank-smart-contracts
  - mkdir -p $TRAVIS_BUILD_DIR/node_modules/chronobank-smart-contracts/node_modules/web3
  - cp -ax $TRAVIS_BUILD_DIR/node_modules/web3 $TRAVIS_BUILD_DIR/node_modules/chronobank-smart-contracts/node_modules
  - cd node_modules/chronobank-smart-contracts && node ../truffle/build/cli.bundled migrate
  - cd $TRAVIS_BUILD_DIR && node node_modules/middleware > /dev/null &
  - cd $TRAVIS_BUILD_DIR/node_modules/middleware && npm run test
  - sleep 30 && cd $TRAVIS_BUILD_DIR && npm run test

script:
  - npm run test -- --coverage

notifications:
  email: false

cache:
  directories:
    - node_modules